# Update your PVC to use the custom storage class
# filepath: /Users/david/Work/kind-clusters/multi-cluster/n8n/n8n-gitops/apps/n8n/base/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: n8n-storage
  resources:
    requests:
      storage: 1Gi